# -*- coding: utf-8 -*-
"""Multi-Agent_Agnos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDfZqVuKFrlKP0BP4mOhG5wBea09PXOd
"""

!pip install agno openai arxiv pypdf duckduckgo-search ddgs

# Set your OpenAI API key directly inside Python
import os
os.environ["OPENAI_API_KEY"] = ""   # <<< REPLACE THIS

# Import Agno tools & classes
from agno.agent import Agent
from agno.team import Team
from agno.models.openai import OpenAIChat
from agno.tools.arxiv import ArxivTools
from agno.tools.duckduckgo import DuckDuckGoTools

# --------------------------
# ArXiv Research Agent
# --------------------------
research_agent = Agent(
    name="ArXiv Research Agent",
    model=OpenAIChat(id="gpt-4o"),
    tools=[ArxivTools()],
    instructions="""
    Your role is to perform academic research.
    1. Search arXiv for highly relevant papers on the topic.
    2. Retrieve the top 3 papers.
    3. Summarize important findings, authors, methods, and contributions.
    """,
    markdown=True,
)

# --------------------------
# Web Search Agent
# --------------------------
web_agent = Agent(
    name="Web Search Agent",
    model=OpenAIChat(id="gpt-4o"),
    tools=[DuckDuckGoTools()],
    instructions="""
    Your role is to research practical real-world context.
    1. Search the broader web for news, articles, and applications.
    2. Identify real implementations, companies using the technology,
       and any industry challenges.
    3. Summarize trends, insights, and debates.
    """,
    markdown=True,
)

# --------------------------
# Research Team (Multi-Agent)
# --------------------------
research_team = Team(
    name="Research Team",
    model=OpenAIChat(id="gpt-4o"),
    members=[research_agent, web_agent],
    instructions="""
    Your job as the team coordinator:
    1. Ask the ArXiv Research Agent for academic papers.
    2. Ask the Web Search Agent for practical applications.
    3. Combine findings from both agents.
    4. Produce one unified, comprehensive research report.
    """,
    show_members_responses=True,
    markdown=True,
)

# --------------------------
# Run the Multi-Agent Workflow
# --------------------------
topic = input("🔬 Enter a research topic: ").strip()
research_team.print_response(f"Research: {topic}", stream=True)

from agno.agent import Agent
from agno.team import Team
from agno.tools.arxiv import ArxivTools
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.models.openai import OpenAIChat

# =============================
# 1️⃣ RETRIEVAL AGENT — Academic Search
# =============================
retrieval_agent = Agent(
    name="Retrieval Agent",
    model=OpenAIChat(id="gpt-4o"),
    tools=[ArxivTools()],
    instructions="""
    Search and retrieve the most recent and relevant academic papers from arXiv.
    Return concise structured data:
    - title
    - authors
    - abstract (<= 3 lines)
    - url
    - year
    """
)

# =============================
# 2️⃣ SOCIAL AGENT — Web / Discussion Search
# =============================
social_agent = Agent(
    name="Social Agent",
    model=OpenAIChat(id="gpt-4o"),
    tools=[DuckDuckGoTools()],
    instructions="""
    Find social or web discussions (Twitter, Reddit, blogs, news) related to the topic or retrieved papers.
    Extract:
    - post title / snippet
    - source (reddit/twitter/blog)
    - engagement or relevance
    - url
    """
)

# =============================
# 3️⃣ ANALYZER AGENT — Data Insight Extraction
# =============================
analyzer_agent = Agent(
    name="Analyzer Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="""
    Analyze the academic and social data.
    Identify:
    - key themes or claims in papers
    - overlap or divergence with public discourse
    - notable datasets, methods, or concerns mentioned
    Return a structured insight list.
    """
)

# =============================
# 4️⃣ CORRELATION AGENT — Cross-Domain Linking
# =============================
correlation_agent = Agent(
    name="Correlation Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="""
    Correlate findings:
    - Identify if papers with strong claims are discussed more online
    - Detect shared topics or sentiment alignment
    Return summarized patterns and 2-3 clear cross-domain links.
    """
)

# =============================
# 5️⃣ VISUALIZER AGENT — Dashboard / Table Builder
# =============================
visualizer_agent = Agent(
    name="Visualizer Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="""
    Create a table summarizing:
    - Paper Title
    - Year
    - Top Social Mention or Discussion
    - Observed Theme / Insight
    Format it clearly in Markdown.
    """
)

# =============================
# 6️⃣ PUBLISHER AGENT — Result Formatting / Output
# =============================
publisher_agent = Agent(
    name="Publisher Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="""
    Format the final multi-agent output for publication or sharing.
    Include a short executive summary (3 lines) followed by the table and insights.
    """
)

# =============================
# 7️⃣ PLANNER TEAM — Workflow Orchestration
# =============================
planner_team = Team(
    name="Research Planner",
    model=OpenAIChat(id="gpt-4o"),
    members=[
        retrieval_agent,
        social_agent,
        analyzer_agent,
        correlation_agent,
        visualizer_agent,
        publisher_agent
    ],
    instructions="""
    Coordinate a full research-social workflow:
    1. Ask Retrieval Agent for papers.
    2. Pass results to Social Agent to find related discussions.
    3. Send combined data to Analyzer and Correlation Agents.
    4. Use Visualizer Agent to create structured tables.
    5. Send final summary to Publisher Agent.
    Return a cohesive report with clear structure.
    """
)

# =============================
# 8️⃣ RUN
# =============================
planner_team.print_response(
    "Research AI agents in healthcare — analyze both academic and public discussion trends.",
    stream=True
)



from textwrap import dedent
from agno.agent import Agent
from agno.team import Team
from agno.models.openai import OpenAIChat
from agno.tools.arxiv import ArxivTools
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.tools.wikipedia import WikipediaTools

# === Agents ===
retrieval_agent = Agent(
    name="Retrieval Agent",
    model=OpenAIChat(id="gpt-4o"),
    tools=[ArxivTools()],
    instructions="Find recent academic papers with title, authors, abstract (≤3 lines), and URL."
)

web_agent = Agent(
    name="Web Agent",
    model=OpenAIChat(id="gpt-4o"),
    tools=[DuckDuckGoTools(), WikipediaTools()],
    instructions="Search the open web and Wikipedia for related discussions or context."
)

analyzer_agent = Agent(
    name="Analyzer Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="Compare academic and web content; find overlaps and emerging themes."
)

correlation_agent = Agent(
    name="Correlation Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="Link papers and public discussions to reveal alignment or divergence."
)

visualizer_agent = Agent(
    name="Visualizer Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="Generate a Markdown table summarizing Paper | Year | Source | Theme."
)

publisher_agent = Agent(
    name="Publisher Agent",
    model=OpenAIChat(id="gpt-4o"),
    instructions="Compose a short executive summary followed by the table."
)

# === Team ===
planner_team = Team(
    name="Open Research Team",
    model=OpenAIChat(id="gpt-4o"),
    members=[
        retrieval_agent,
        web_agent,
        analyzer_agent,
        correlation_agent,
        visualizer_agent,
        publisher_agent
    ],
    instructions=dedent("""
    1. Retrieve academic papers (ArXiv)
    2. Gather open-web context (DuckDuckGo/Wikipedia)
    3. Analyze & correlate findings
    4. Produce Markdown summary table
    5. Output final report
    """)
)

# === Input box for topic ===
topic = input("🧠 Enter your research topic: ").strip()

print("\n🚀 Running multi-agent research workflow...\n")
planner_team.print_response(topic, stream=True)

